cartlane/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master/', views.Master, name='master'),
    path('', views.Index, name='index'),

    path('signup', views.signup, name='signup'),
    path('account/',include('django.contrib.auth.urls')),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),


    # AddToCart    
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
    
    
    # ProductDetails
    path('category/<str:id>', views.category, name='category'),
    path('product/<str:id>',views.product_details,name='product_detail'),


    # Inventory
    path('inventory_login', views.inventory_login, name='inventory_login'),
    path('inventory',views.inventory, name='inventory'),
    path('inventory_add',views.inventory_add, name='inventory_add'),
    path('inventory_update/<int:id>',views.inventory_update, name='inventory_update'),
    path('inventory_delete/<int:id>',views.inventory_delete, name='inventory_delete'),
    
    
    # Diamond
    path('diamond', views.diamond, name='diamond'),
    path('diamond_add', views.diamond_add, name='diamond_add'),
    path('diamond/<str:id>',views.diamond_details,name='diamond_detail'),
    path('diamond_update/<str:id>',views.diamond_update,name='diamond_update'),
    path('diamond_delete/<str:id>',views.diamond_delete,name='diamond_delete'),
    
    
    # Search
    path('search/',views.search,name='search'),
    
    
    
    




] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

jewellery/models.py
from django.db import models

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to='jewellery/categoryimg', null=True)
    
    def __str__(self) -> str:
        return self.name


class Sub_Category(models.Model):
    name = models.CharField(max_length=150)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name
    

class Product(models.Model):
    color_type = (
        ('Gold','Gold'),
        ('Red','Red'),
        ('Green','Green'),
        ('Blue','Blue'),
        ('Orange','Orange'),
        ('Black','Black'),
        ('Peal','Peal'),
    )
    
    category = models.ForeignKey(Category, on_delete= models.CASCADE, null= True, default="")
    sub_category = models.ForeignKey(Sub_Category, on_delete= models.CASCADE, null= True, default="")
    image = models.ImageField(upload_to='jewellery/pimg')
    name = models.CharField(max_length=100)
    meta_title = models.CharField(max_length=150, default="Meta_title descrpition here")
    desc = models.TextField(default="Descrpition here")
    add_info = models.TextField(default="NO Additonal Info")
    color =  models.CharField(choices=color_type,max_length=10,default="Gold")
    price = models.IntegerField()
    date = models.DateField(auto_now_add=True)
    status = models.BooleanField(default=True)
    favourite = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name +" "+ self.sub_category.name + " "+ self.category.name    
    class Meta:
        db_table = "product"
        
        

class Diamond(models.Model):
    shape_type = (
        ('round',' Round'),
        ('princess',' Princess'),
        ('pear',' Pear'),
        ('heart',' Heart'),
        ('asscher',' Asscher'),
        ('cushion',' Cushion'),
        ('oval',' Oval'),
        ('radiant',' Radiant'),
    )
    
    color_type = (
        ('D','D'),
        ('E','E'),
        ('F','F'),
        ('G','G'),
        ('H','H'),
        ('I','I'),
        ('J','J'),
        ('K','K'),
    )
    
    clarity_type = (
        ('FL','FL'),
        ('IF','IF'),
        ('VVS1','VVS1'),
        ('VVS2','VVS2'),
        ('VS1','VS1'),
        ('VS2','VS2'),
        ('SI1','SI1'),
        ('SI2','SI2'),
    )
    
    cut_type = (
        ('H&A','H&A'),
        ('Excellent', 'Excellent'),
        ('V Good','V Good'),
        
    )
    
    symmetry_type = (
        ('Excellent', 'Excellent'),
        ('V Good','V Good'),   
        ('Good','Good'),
    )
    
    image = models.ImageField(upload_to='jewellery/diamondimg')
    name = models.CharField(max_length=100)
    meta_title = models.CharField(max_length=150, default="Meta_title descrpition here")
    desc = models.TextField(default="Descrpition here")
    add_info = models.TextField(default="NO Additonal Info")
    shape =  models.CharField(choices=shape_type,max_length=50,default="round")
    carat = models.FloatField()
    color =  models.CharField(choices=color_type,max_length=10,default="D")
    clarity =  models.CharField(choices=clarity_type,max_length=50,default="FL")
    cut =  models.CharField(choices=cut_type,max_length=50,default="H&A")
    symmetry =  models.CharField(choices=symmetry_type,max_length=50,default="Excellent")
    price = models.IntegerField()
    date = models.DateField(auto_now_add=True)
    status = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name 
    
    


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required= True, label= 'Email', error_messages= {'exits': 'This is Already Exists'})

    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)
        
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'


    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError(self.fields['email'].error_message['exists'])   
        return self.cleaned_data['email'] 

templates/product/inventory.html
{% extends 'master.html' %}
{% block body %}  

<div class="mb-2"></div><!-- End .mb-2 -->
<div class="container">
    <div class="row float-right">
        <div class="">
            <div class="btn-wrap">
                <a href="inventory_add" class="btn btn-primary btn-rounded">Add Product</a>
            </div><!-- End .btn-wrap -->
        </div><!-- End .col-md-4 col-lg-2 -->

        <div class="col-md-4 col-lg-2">
            <div class="btn-wrap">
                <a href="diamond_add" class="btn btn-primary btn-rounded">Add Diamond</a>
            </div><!-- End .btn-wrap -->
        </div><!-- End .col-md-4 col-lg-2 -->
    </div><!-- End .row -->
</div>

<div class="container">
<h4>Product</h4>
<div class="table-reponsive box">
    <table id="example" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Category</th>
                    <th>Sub-Category</th>
                    <th>Color</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for prod in product %}
                <tr>
                    <td><a href="product/{{prod.id}}"><img src={{prod.image}} height="100" width="100"/></a></td>
                    <td><a href="product/{{prod.id}}">{{prod.name}}</a></td>
                    <td>{{prod.price}}</td>
                    <td>{{prod.category.name}}</td>
                    <td>{{prod.sub_category.name}}</td>
                    <td>{{prod.color}}</td>
                    <td><a href="/inventory_update/{{ prod.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a> <a href="/inventory_delete/{{ prod.id }}"><span class="glyphicon glyphicon-trash" >delete</span></a> </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if product.has_previous %}
            <li class="page-item">
                <a class="page-link page-link-prev" href="{% url 'inventory' %}?productpage={{product.previous_page_number}}" aria-label="Previous" tabindex="-1" aria-disabled="true">
                    <span aria-hidden="true"><i class="icon-long-arrow-left"></i></span>Prev
                </a>
            </li>
            {% endif %}
            {% if product.has_next %}
            <li class="page-item">
                <a class="page-link page-link-next" href="{% url 'inventory' %}?productpage={{product.next_page_number}}" aria-label="Next">
                    Next <span aria-hidden="true"><i class="icon-long-arrow-right"></i></span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>	
</div>


<div class="container">
    <h4>Diamond</h4>
    <div class="table-reponsive box">
        <table id="example" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Carat</th>
                        <th>Clarity</th>
                        <th>Color</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for dia in diamond %}	
                    <tr>
                        <td><a href="diamond/{{dia.id}}"><img src={{dia.image}} height="100" width="100"/></a></td>
                        <td><a href="diamond/{{dia.id}}">{{dia.name}}</a></td>
                        <td>{{dia.price}}</td>
                        <td>{{dia.carat}}</td>
                        <td>{{dia.clarity}}</td>
                        <td>{{dia.color}}</td>
                        <td><a href="/diamond_update/{{ dia.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a> <a href="/diamond_delete/{{ dia.id }}"><span class="glyphicon glyphicon-trash" >delete</span></a> </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if diamond.has_previous %}
                <li class="page-item">
                    <a class="page-link page-link-prev" href="{% url 'inventory' %}?page={{diamond.previous_page_number}}" aria-label="Previous" tabindex="-1" aria-disabled="true">
                        <span aria-hidden="true"><i class="icon-long-arrow-left"></i></span>Prev
                    </a>
                </li>
                {% endif %}
                {% if diamond.has_next %}
                <li class="page-item">
                    <a class="page-link page-link-next" href="{% url 'inventory' %}?page={{diamond.next_page_number}}" aria-label="Next">
                        Next <span aria-hidden="true"><i class="icon-long-arrow-right"></i></span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>	
    </div>
{% comment %} 

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Category</h2>
                    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                        <div class="panel panel-default">
                            <div class="panel-heading">
                               <h4 class="panel-title">
                                <a href="{% url 'inventory'%}">All</a>
                            </h4>
                            </div>
                        </div>

                        {% for cat in category %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                        {{cat.name}}
                                    </a>
                                </h4>
                            </div>
                            <div id="{{cat.id}}" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <ul>
                                        {% for i in cat.sub_category_set.all %}
                                        <li><a href="?category={{i.id}}">{{i.name}} </a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                           <h4 class="panel-title">
                            <a href="#diamond">Diamonds</a>
                        </h4>
                        </div>
                    </div>
                    </div><!--/category-products-->
                
                </div>
            </div>
            
            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Inventory</h2>
                    {% for prod in product %}
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products">
                                    <div class="productinfo text-center">
                                        <img src="{{prod.image}}" alt="" />
                                        <h2>{{prod.price}}</h2>
                                        <p>{{prod.name}}</p>
                                    </div>
                                    
                            </div>
                            <div class="choose">
                                <ul class="nav nav-pills nav-justified">
                                    <li><a href="product/{{prod.id}}"><i class="fa fa-plus-square"></i>View</a></li>
                                    <li><a href="/inventory_update/{{ prod.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a> </li>
                                    <li><a href="/inventory_delete/{{ prod.id }}"><span class="glyphicon glyphicon-trash" >delete</span></a> </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    {% endfor %}
                </div><!--features_items-->



                <div class="recommended_items" id="diamond"><!--diamonds-->
                    <h2 class="title text-center">Diamonds</h2>
                    <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="item active">
                                {% for dia in diamond %}	
                                <div class="col-sm-4">
                                    <div class="product-image-wrapper">
                                        <div class="single-products">
                                            <div class="productinfo text-center">
                                                <img src="{{dia.image.url}}" alt="" />
                                                <h2>{{dia.name}}</h2>
                                                <p>{{dia.price}}</p>
                                            </div>
                                            <div class="choose">
                                                <ul class="nav nav-pills nav-justified">
                                                    <li><a href="product/{{prod.id}}"><i class="fa fa-plus-square"></i>View</a></li>
                                                    <li><a href="/inventory_update/{{ prod.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a> </li>
                                                    <li><a href="/inventory_delete/{{ prod.id }}"><span class="glyphicon glyphicon-trash" >delete</span></a> </li>
                                                </ul>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                         <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
                            <i class="fa fa-angle-left"></i>
                          </a>
                          <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
                            <i class="fa fa-angle-right"></i>
                          </a>			
                    </div>
                </div><!--/diamonds-->
                
                
                
            </div>
        </div>
    </div>
</section> {% endcomment %}
{% endblock %}

templates/product/product.html
{% extends 'master.html' %}
{% block body %}  



<main class="main">
    <div class="page-header text-center" style="background-image: url('https://cdn.shopify.com/s/files/1/0441/4020/0089/articles/Diamond-Banner-02_1650x.jpg?v=1605760011')">
        <div class="container">
            <h1 class="page-title">Diamonds</span></h1>
        </div><!-- End .container -->
    </div><!-- End .page-header -->
    <nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item"> {{category1}}</li>
            </ol>
        </div><!-- End .container -->
    </nav><!-- End .breadcrumb-nav -->

    <div class="page-content">
        <h4 style="text-align: center">{{category1}}</h4>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="entry-container max-col-2" data-layout="fitRows">
                        {% if product1 %}
                        {% for prod in product1 %}
                        <div class="entry-item col-sm-3">
                            <article class="entry entry-grid">
                                <figure class="entry-media">
                                    <a href="http://127.0.0.1:8000/product/{{prod.id}}">
                                        <img src="{{prod.image.url}}" alt="image desc">
                                    </a>
                                </figure><!-- End .entry-media -->

                                <div class="entry-body">
                                    <div class="entry-meta">
                                        
                                    </div><!-- End .entry-meta -->

                                    <h2 class="entry-title">
                                        <a href="single.html">{{prod.name}}</a>
                                    </h2><!-- End .entry-title -->

                                    <div class="entry-cats">
                                        <h4>&#8377; {{prod.price}}</h4>
                                    </div><!-- End .entry-cats -->
                                    
                                </div><!-- End .entry-body -->

                            </article><!-- End .entry -->
                        </div><!-- End .entry-item -->
                        {% endfor %}
                        {% else %}
                        <h3>No Product Found</h3>

                        {% endif %}
                    </div><!-- End .entry-container -->

                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            {% if items.has_previous %}
                            <li class="page-item">
                                <a class="page-link page-link-prev" href="{% url 'diamond' %}?page={{items.previous_page_number}}" aria-label="Previous" tabindex="-1" aria-disabled="true">
                                    <span aria-hidden="true"><i class="icon-long-arrow-left"></i></span>Prev
                                </a>
                            </li>
                            {% endif %}
                            {% if items.has_next %}
                            <li class="page-item">
                                <a class="page-link page-link-next" href="{% url 'diamond' %}?page={{items.next_page_number}}" aria-label="Next">
                                    Next <span aria-hidden="true"><i class="icon-long-arrow-right"></i></span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                    <p>Showing page {{page_num}} of pages {{all_page}}</p>

                </div><!-- End .col-lg-9 -->
            </div><!-- End .row -->
        </div><!-- End .container -->
    </div><!-- End .page-content -->
</main><!-- End .main -->


{% comment %} 
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Category</h2>
                    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                        {% for cat in category %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                        {{cat.name}}
                                    </a>
                                </h4>
                            </div>
                            <div id="{{cat.id}}" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <ul>
                                        {% for i in cat.sub_category_set.all %}
                                        <li><a href="?subcategory={{i.id}}">{{i.name}} </a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                    
                    <div class="shipping text-center"><!--shipping-->
                        <img src="/static/images/home/shipping.jpg" alt="" />
                    </div><!--/shipping-->
                
                </div>
            </div>

            <div class="col-sm-9">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center"> {{category1}}</h2>
                    {% for prod in product1 %}
                    <div class="col-sm-3">
                        <div class="product-image-wrapper">
                            <div class="single-products">
                                    <div class="productinfo text-center">
                                        <img src="{{prod.image.url}}" alt=""  width="100" height="200"/>
                                        <h2>{{prod.price}}</h2>
                                        <p>{{prod.name}}</p>
                                        <p><i>{{prod.sub_category.name}}</i></p>
            
                                    </div>
                            
                            </div>
                            <div class="choose">
                                <ul class="nav nav-pills nav-justified">
                                    <li><a href="/product/{{prod.id}}"><i class="fa fa-plus-square"></i>View Product</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    {% endfor %}
                </div><!--features_items-->
                
            </div>
            
        </div>
    </div>
</section> {% endcomment %}



{% endblock %}